output:
  sort-results: true

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
        - paralleltest
      text: "does not use range value in test Run"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gci:
    local-prefixes: github.com/invidian/golang-cli-testing-example
  godot:
    capital: true
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  makezero:
    always: true
  nolintlint:
    allow-leading-space: false
    require-explanation: true
    require-specific: true
  wsl:
    force-err-cuddling: true

linters:
  disable:
    # Allow not always explicitly specifying all fields of the struct, make use of zero values.
    - exhaustivestruct
    # Allow using dynamic errors, as static errors are mainly useful for larger APIs.
    - goerr113
    # To allow defensive approach when initializing structs.
    - ireturn
    # Currently panics on the code and we do not have prometheus metrics anyway.
    # See https://github.com/yeya24/promlinter/issues/32 for more details.
    - promlinter
    # Those linters are deprecated.
    - interfacer
    - maligned
    - golint
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - ifshort
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
